[program:browser-firefox]
command=/bin/bash -c "sleep 5 && firefox https://client.freemchosting.com/dashboard"
autostart=true
autorestart=true
startsecs=10
startretries=5
stdout_logfile=/var/log/browser-firefox.log
stderr_logfile=/var/log/browser-firefox.err
environment=DISPLAY=":99"
